import pg from "pg";
const pool = new pg.Pool({connectionString: process.env.DATABASE_URL || "postgresql://postgres:qclVcOrQtiQmeovPWAAwXdunduEzpCmC@autorack.proxy.rlwy.net:43824/railway"});
const r = await pool.query("SELECT original_ingredient, COUNT(*) as cnt FROM substitutions WHERE original_ingredient LIKE '%sugar%' GROUP BY original_ingredient ORDER BY cnt DESC LIMIT 10");
console.log("Sugar-related original ingredients:", JSON.stringify(r.rows, null, 2));
const r2 = await pool.query("SELECT DISTINCT original_ingredient FROM substitutions WHERE original_ingredient = 'sugar'");
console.log("Exact 'sugar' matches:", r2.rows.length);
const r3 = await pool.query("SELECT COUNT(*) as total FROM substitutions");
console.log("Total substitution pairs:", r3.rows[0].total);
const r4 = await pool.query("SELECT name FROM ingredients WHERE name LIKE '%sugar%' LIMIT 10");
console.log("Ingredients with sugar:", JSON.stringify(r4.rows));
await pool.end();
